/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.recipe;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication()
@ComponentScan
public class RecipeApp {
	public static void main(String[] args) {
		SpringApplication.run(RecipeApp.class, args);
	}
}
